name: Test search

on:
  push:
    paths:
      - '!README.md'
      - 'src/**.py'
      - 'utils/**.py'
      - 'utils/**.mjs'
      - '.github/workflows/**.yml'
      - '**.py'
      - 'google.spec'
      - 'google'
    branches:
      - 'main'
      - 'dev'
      - '!feat/**'
  pull_request:
    type: [opened, reopened, synchronize]
    paths:
      - '!README.md'
      - 'src/**.py'
      - 'utils/**.py'
      - 'utils/**.mjs'
    branches:
      - 'main'
      - 'dev'
      - '!feat/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node dependencies
        run: npm install

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Build and test application
        run: | 
          python3 -m PyInstaller google.spec
          python3 search_test.py

